version: '3.8'
services:
    cloud9:
        restart: always
        hostname: cloud9
        container_name: cloud9
        image: linuxserver/cloud9:latest
        environment:
          PUID: 0
          PGID: 0
          TZ: "Asia/Jerusalem"
        volumes:
          - /home/dima/docker-mounts:/code
          - /home/dima/platesMigration:/code/platesMigration
          - /var/run/docker.sock:/var/run/docker.sock
        network_mode: "bridge"
        ports:
          - "8000:8000"


    homeassistant:
        restart: always
        hostname: homeassistant
        container_name: Home-Assistant
        image: homeassistant/home-assistant:stable
        depends_on: 
          - mariadb
          - mqtt
          - nginx
        labels:
          com.ouroboros.enable: "false"
        environment:
          TZ: "Asia/Jerusalem"
          USER: ${HA_USER}
          PASS: ${HA_PASS}
        volumes:
          - /home/dima/docker-mounts/ha:/config
        network_mode: "host"

    portainer:
        restart: always
        hostname: portainer
        container_name: Portrainer
        image: portainer/portainer-ce
        environment:
          TZ: "Asia/Jerusalem"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /opt/portainer:/data
        network_mode: "bridge"
        ports:
          - "9000:9000"

    ftpserver:
        restart: always
        hostname: ftp-server
        container_name: ftp-server
        image: mauler/simple-ftp-server
        environment:
          TZ: "Asia/Jerusalem"
          FTP_USER: ${FTP_USER}
          FTP_PASS: ${FTP_PASS}
        mac_address: 00:00:ff:ff:ff:01
        volumes:
          - /media/dima/RouterHDD/ftp:/ftp-home
        ports:
          - "11021:21"
    

    nginx: 
      restart: always
      image: nginx:latest
      container_name: nginx
      privileged: true
      environment:
        PUID: 0
        PGID: 0
      volumes:
        - /home/dima/docker-mounts/nginx/etc/nginx:/etc/nginx
        - /home/dima/docker-mounts/certbot/etc/letsencrypt:/etc/letsencrypt
        - /home/dima/docker-mounts/certbot/www:/var/www/certbot
        - /media/dima/RouterHDD/ftp:/ftp
      network_mode: "host"

    pihole:
      container_name: pihole
      hostname: pihole
      image: pihole/pihole:latest
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "1080:80/tcp"
        - "10443:443/tcp"
      environment:
        TZ: 'Asia/Jerusalem'
        WEBPASSWORD: ${PIHOLE_PASS}
      volumes:
        - '/home/dima/docker-mounts/pihole/etc-pihole/:/etc/pihole/'
        - '/home/dima/docker-mounts/pihole/etc-hosts:/etc/hosts'
        - '/home/dima/docker-mounts/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        - '/home/dima/docker-mounts/pihole/pihole.log:/var/log/pihole.log'
      dns:
        - 127.0.0.1
        - 9.9.9.9
      cap_add:
        - NET_ADMIN
      restart: always
     
volumes:
  sessions:
